server:
  port: 6666
spring:
  ai:
    openai:
      api-key: {DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
        base-url: https://api.deepseek.com
#        api-key: ${DEEPSEEK_API_KEY}/