server:
  port: 8085
spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        type: ASYNC
        name: mcp-server
#        stdio: true
        version: "1.0.0"
#        base-url: http://localhost:8085
        enabled: true
        sse-message-endpoint: /mcp/book
#        capabilities:
#          tool: true
#          resource: true
#          prompt: true
#          completion: true