server:
  port: 6363

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat.model: qwen3:8b
    memory:
      redis:
        host: localhost
        password: redis
  datasource:
    driver-class-name:
  config:
    import:
      - optional:classpath:.env[.properties]
      - classpath:config/qr_code.yml
      - classpath:config/zhi_pu.yml
      - classpath:config/dash_scope.yml
      - classpath:config/vector_store.yml