server:
  port: 6666
spring:
  config:
    import:
    - classpath:config/zhi_pu.yml
    - classpath:config/dash_scope.yml
    - classpath:config/cloud_bed.yml
    - classpath:config/mcp.yml
    - optional:classpath:.env[.properties]
  main:
    allow-bean-definition-overriding: true
  ai:
    model:
      image: zhipuai # 设置 图像处理的 AI 为 智谱 AI
      chat: ollama # 设置 聊天 AI 为 ollama( 本地AI )
      embedding: openai  # 设置 向量生成 AI 为 OpenAI
      audio:
        speech: openai # 设置 语音合成 AI 为 dashscope
        transcription: openai # 设置 语音识别 AI 为 OpenAI
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
        base-url: https://api.deepseek.com
    ollama:
      base-url: http://localhost:11434
      chat.model: qwen3:8b
    openai:
      audio:
        speech:
          api-key: ${SILICONFLOW_API_KEY}
          base-url: https://api.siliconflow.cn
          options:
            #            voice: anna
            model: FunAudioLLM/CosyVoice2-0.5B
      #      base-url:  https://api.siliconflow.cn/v1
      embedding:
        #        enabled: true
        options:
          model: BAAI/bge-m3
          #          max-token: 512/
          dimensions: 1536  # 修改为实际输出维度
        api-key: ${SILICONFLOW_API_KEY}
        base-url: https://api.siliconflow.cn
      api-key: ${DEEPSEEK_API_KEY}
    memory:
      redis:
        host: localhost
        port: 6379
        timeout: 60000
        password: redis
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: kiko
          password: 123456
        databaseName: "default"
        collectionName: "vector_store"  # 使用新集合名避免schema冲突
        embeddingDimension: 1536  # 修改为与embedding模型一致
        indexType: IVF_FLAT
        metricType: COSINE
    retry:
      max-attempts: 10 # 最大尝试次数
  datasource:
    dynamic:
      strict: true
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/deep_seek?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
#        postgresql:
#          url: jdbc:postgresql://localhost:5432/vector
#          username: postgres
#          password: 123456
      primary: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
mybatis-plus:
  mapper-locations: org.deepseek.mapper.*

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
#amap:
#  api-key: ${AMAP_API_KEY}
#  base-url: https://mcp.amap.com

